# -*- coding: utf-8 -*-
"""CH02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOru8Gv4o2VuEyuGLCoVQfuwSIY3nwtc
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/gdrive')

img = cv2.imread('/content/gdrive/My Drive/ColabIP26/Images/lena256.jpg')
cv2_imshow(img)

RGB_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(RGB_img)

Red_img, Green_img, Blue_img = cv2.split(RGB_img)

print(Red_img.shape)

print(RGB_img.shape)

Gray_img = RGB_img

Gray_img[:,:,0] = Red_img
Gray_img[:,:,1] = Red_img
Gray_img[:,:,2] = Red_img

plt.imshow(Gray_img)

HSV_img = cv2.cvtColor(RGB_img, cv2.COLOR_RGB2HSV)

H_img, S_img, V_img = cv2.split(HSV_img)

Gray_img[:,:,0] = S_img
Gray_img[:,:,1] = S_img
Gray_img[:,:,2] = S_img

plt.imshow(Gray_img)

Gray_img[:,:,0] = Green_img
Gray_img[:,:,1] = Green_img
Gray_img[:,:,2] = Green_img

plt.imshow(Gray_img)

Gray_img[:,:,0] = Blue_img
Gray_img[:,:,1] = Blue_img
Gray_img[:,:,2] = Blue_img

plt.imshow(Gray_img)

